# Generated by Django 4.1.7 on 2023-03-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0003_state_region_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.region",
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.state",
                verbose_name="State",
            ),
        ),
    ]
