# Generated by Django 4.1.7 on 2023-03-08 15:01

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0004_alter_location_region_alter_region_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_category",
                to="catalogs.productcategory",
                verbose_name="SubCategory",
            ),
        ),
    ]
