# Generated by Django 4.1.7 on 2023-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0002_rename_deal_type_deal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
