# Generated by Django 4.1.7 on 2023-03-04 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_referralcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralcode",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Referred",
            ),
        ),
    ]
