# Generated by Django 4.1.7 on 2023-03-04 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_referralcode_referred_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralcode",
            name="referred_by",
        ),
        migrations.AddField(
            model_name="referralcode",
            name="referred_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Referred",
            ),
        ),
    ]
