# Generated by Django 4.1.7 on 2023-03-04 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_rename_referred_by_referralcode_referred_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralcode",
            name="referred_users",
        ),
        migrations.AddField(
            model_name="referralcode",
            name="referred_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_referred_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Referred",
            ),
        ),
    ]
