# Generated by Django 4.1.7 on 2023-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_remove_referralcode_referred_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralcode",
            name="code",
            field=models.CharField(max_length=8, verbose_name="Referral Code"),
        ),
    ]
