# Generated by Django 4.1.7 on 2023-03-06 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.location",
                verbose_name="Location",
            ),
        ),
    ]
