# Generated by Django 4.1.7 on 2023-03-08 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_rename_updated_wallet_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
