# Generated by Django 4.1.7 on 2023-03-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0005_alter_productcategory_parent"),
        ("accounts", "0018_userlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlocation",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.location",
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.region",
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogs.state",
                verbose_name="State",
            ),
        ),
    ]
