# Generated by Django 4.1.7 on 2023-03-08 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_alter_userlocation_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlocation",
            name="profile",
        ),
    ]
