# Generated by Django 4.1.7 on 2023-03-09 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_transaction_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
