# Generated by Django 4.1.7 on 2023-03-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0002_rename_message_ticket_alter_ticket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/", verbose_name="Image"
            ),
        ),
    ]
