# Generated by Django 4.1.7 on 2023-03-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0004_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-timestamp"], "verbose_name": "Tickets"},
        ),
        migrations.AlterField(
            model_name="reply",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/", verbose_name="Image"
            ),
        ),
    ]
