# Generated by Django 4.1.7 on 2023-03-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_location"),
        ("products", "0003_productprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="available_points",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterUniqueTogether(
            name="productprice",
            unique_together={("product", "location")},
        ),
    ]
