# Generated by Django 4.1.7 on 2023-03-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_active_product_available_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Sold Count"),
        ),
    ]
